In [13]:
import os
from os.path import join
import nibabel as nib
from skimage.measure import label, regionprops
import numpy as np
import math
import matplotlib.pyplot as plt
import cv2
import pandas as pd

In [14]:
def connected_component_analysis(seg, thr=0.5):
    #print(type(seg), seg.shape, seg.min(), seg.max())
    mask = seg.copy()
    mask[mask > thr] = 255
    mask[mask <= thr] = 0

    lbl = label(mask)
    blobs = regionprops(lbl)
    #raw_bbox_list = [b.bbox for b in blobs]
    #axis_major_length_list = [b.axis_major_length for b in blobs]

    return blobs

def cystregionprops(r):
    area = r.area
    major = round(r.axis_major_length, 3)
    
    try:
        minor = round(math.sqrt(10 * (-r.inertia_tensor_eigvals[0] + r.inertia_tensor_eigvals[1] + r.inertia_tensor_eigvals[2])), 3)
    except ValueError:
        minor = np.nan

    return (area, major, minor)


In [15]:
# Folder path
#seg_folder_path = r'C:\Users\pky0507\Desktop\ilkin\pancreas_ipmn\temporary_folder_cyst_segmentations\allegheny\cyst_segmentation'
#mri_folder_path = r'C:\Users\pky0507\Desktop\ilkin\pancreas_ipmn\allegheny\reoriented'

seg_folder_path = '/data/ayc9699/dataset/pancreas_ipmn_ilkin/temporary_folder_cyst_segmentations/allegheny/cyst_segmentation'
mri_folder_path = '/data/ayc9699/dataset/pancreas_ipmn_ilkin/allegheny/reoriented'

# List to store file paths
seg_file_paths = []
mri_file_paths = []
ids = []

# Iterate over files in the folder
for root, dirs, files in os.walk(seg_folder_path):
    for file in files:
        file_path = os.path.join(root, file)
        if file.startswith(".") : continue
        seg_file_paths.append(file_path)

# Print the file paths
for path in seg_file_paths:
    id = path.split("/")[-1].split(".")[:-2][-2:]
    if id==[]: continue
    id = id[-1][-2:]
    print(id)
    mri_file_paths.append(os.path.join(mri_folder_path, f"ahn_{id}.nii.gz"))


21
58
41
80
02
11
27
09
23
61
29
16
51
77
12
19
48
05
54
35
28


In [16]:
for i in range(len(seg_file_paths)):
    print(f"pair {i+1}")
    print(seg_file_paths[i-1], "\n", mri_file_paths[i-1])

#print(len(seg_file_paths), len(mri_file_paths))

pair 1
/data/ayc9699/dataset/pancreas_ipmn_ilkin/temporary_folder_cyst_segmentations/allegheny/cyst_segmentation/AHN28.nii.gz 
 /data/ayc9699/dataset/pancreas_ipmn_ilkin/allegheny/reoriented/ahn_28.nii.gz
pair 2
/data/ayc9699/dataset/pancreas_ipmn_ilkin/temporary_folder_cyst_segmentations/allegheny/cyst_segmentation/AHN21.nii.gz 
 /data/ayc9699/dataset/pancreas_ipmn_ilkin/allegheny/reoriented/ahn_21.nii.gz
pair 3
/data/ayc9699/dataset/pancreas_ipmn_ilkin/temporary_folder_cyst_segmentations/allegheny/cyst_segmentation/AHN58.nii.gz 
 /data/ayc9699/dataset/pancreas_ipmn_ilkin/allegheny/reoriented/ahn_58.nii.gz
pair 4
/data/ayc9699/dataset/pancreas_ipmn_ilkin/temporary_folder_cyst_segmentations/allegheny/cyst_segmentation/AHN41.nii.gz 
 /data/ayc9699/dataset/pancreas_ipmn_ilkin/allegheny/reoriented/ahn_41.nii.gz
pair 5
/data/ayc9699/dataset/pancreas_ipmn_ilkin/temporary_folder_cyst_segmentations/allegheny/cyst_segmentation/AHN80.nii.gz 
 /data/ayc9699/dataset/pancreas_ipmn_ilkin/allegheny/

In [17]:

def create_df():
    column_names=['Center', 'Patient', 'Pancreas_volume_ml', 'Cyst_volume_ml', 'Panc_Cyst_volume_ml', 'Diagonal_mm', 'Panc_vol_to_Diagonal', 'Num_of_Cysts']
    # Add columns using a for loop

    # Define the number of cysts
    num_cysts = 3
    for i in range(num_cysts):
        area_column_name = f'Cyst_{i+1}_vol_ml'
        major_column_name = f'Cyst_{i+1}_major_mm'
        minor_column_name = f'Cyst_{i+1}_minor_mm'
        column_names.append(area_column_name)
        column_names.append(major_column_name)
        column_names.append(minor_column_name)

    # Create an empty DataFrame
    df = pd.DataFrame(columns = column_names)

    df.head()
    return df

In [18]:

def largest3rs(r_list, voxel_sizes):
    voxel_sizes = [voxel_sizes[2], voxel_sizes[1], voxel_sizes[0]]
    sorted_r = sorted(r_list, key=lambda r: r.axis_major_length, reverse=True)
    top_3 = []
    
    for r in sorted_r[:3]:

        
        cov_matrix = r.inertia_tensor

        # Perform eigendecomposition to obtain eigenvectors and eigenvalues
        eigenvalues, eigenvectors = np.linalg.eigh(cov_matrix)

        # Determine the dimension along which the major and minor axes lie
        major_axis_dimension = np.argmax(eigenvalues)
        minor_axis_dimension = np.argmin(eigenvalues)

        # Multiply the measurements by the corresponding voxel sizes
        axis_major_length_mm = r.major_axis_length * voxel_sizes[major_axis_dimension]
        try:
            axis_minor_length_mm = r.minor_axis_length * voxel_sizes[minor_axis_dimension]
        except ValueError:
            axis_minor_length_mm = np.nan
        
        # Use the calculated measurements and axis dimensions as needed
        #print(f"Axis Major Length (mm): {axis_major_length_mm}, Dimension: {major_axis_dimension}")
        #print(f"Axis Minor Length (mm): {axis_minor_length_mm}, Dimension: {minor_axis_dimension}")

        vol_ml = r.area * voxel_sizes[0] * voxel_sizes[1] * voxel_sizes[2]/1000
        #major = round(r.axis_major_length, 3)
        
        axis_major_length_mm = round(axis_major_length_mm, 3)
        #axis_minor_length_mm = round(axis_minor_length_mm, 3)
        
        try:
            axis_minor_length_mm = r.minor_axis_length * voxel_sizes[minor_axis_dimension]
        except ValueError:
            axis_minor_length_mm = np.nan
        '''
        try:
            minor = round(math.sqrt(10 * (-r.inertia_tensor_eigvals[0] + r.inertia_tensor_eigvals[1] + r.inertia_tensor_eigvals[2])), 3)
        except ValueError:
            minor = np.nan
        '''        
        
        top_3.append((vol_ml, axis_major_length_mm, axis_minor_length_mm))
        #top_3.append((area, major, minor))

    
    return top_3


In [19]:
'''
def largest3rs(r_list):
    sorted_r = sorted(r_list, key=lambda r: r.axis_major_length, reverse=True)
    top_3 = []
    
    for r in sorted_r[:3]:
        area = r.area
        major = round(r.axis_major_length, 3)
        
        try:
            minor = round(math.sqrt(10 * (-r.inertia_tensor_eigvals[0] + r.inertia_tensor_eigvals[1] + r.inertia_tensor_eigvals[2])), 3)
        except ValueError:
            minor = np.nan
        
        top_3.append((area, major, minor))
    
    return top_3
    '''


'\ndef largest3rs(r_list):\n    sorted_r = sorted(r_list, key=lambda r: r.axis_major_length, reverse=True)\n    top_3 = []\n    \n    for r in sorted_r[:3]:\n        area = r.area\n        major = round(r.axis_major_length, 3)\n        \n        try:\n            minor = round(math.sqrt(10 * (-r.inertia_tensor_eigvals[0] + r.inertia_tensor_eigvals[1] + r.inertia_tensor_eigvals[2])), 3)\n        except ValueError:\n            minor = np.nan\n        \n        top_3.append((area, major, minor))\n    \n    return top_3\n    '

In [20]:
from skimage.measure import label, regionprops
import numpy as np
def compute_diagonal_length_3D(image, voxel_size_x, voxel_size_y, voxel_size_z):
    # Ensure that image is a binary image
    #print(image.shape)
    assert np.array_equal(image, image.astype(bool)), "Input should be a binary image"

    # Label the image
    labeled_image = label(image)
    #print(np.unique(labeled_image))

    # Compute the properties of the labeled regions
    regions = regionprops(labeled_image)

    # Initialize list to store diagonal lengths
    diagonals = []
    #print("voxel",voxel_size_x, voxel_size_y, voxel_size_z)
    for region in regions:
        # Get the bounding box coordinates
        minp, minr, minc, maxp, maxr, maxc = region.bbox
        # Compute the width, height, and depth of the box
        width = (maxp - minp) * voxel_size_x
        height = (maxr - minr) * voxel_size_y
        depth = (maxc - minc) * voxel_size_z
        #print("debug--------", "depth:", (maxc - minc), "y ekseni:", (maxr - minr),  "x ekseni:", (maxp - minp))
        #print(region.bbox, width, height, depth)

        # Use Pythagorean theorem to compute the diagonal length
        diagonal = np.sqrt(width**2 + height**2 + depth**2)
        diagonals.append(diagonal)

    return diagonals

In [21]:
def get_volume_ml(label, voxel_vol_mm3):
    volume_mm3 = np.sum(label != 0) * voxel_vol_mm3
    volume_ml = volume_mm3 / 1000
    return volume_ml

In [26]:
#fig, axs = plt.subplots(1, 3, figsize=(15, 5))

df = create_df()

for eachpatientind in range(len(seg_file_paths)):
    
    pt_name = seg_file_paths[eachpatientind].split("/")[-1].split(".")[0][-2:]
    print(pt_name)
    #if seg_file_paths[eachpatientind].split("\\")[-1].split("_")[-1] == 'pass.nii': continue
    #if pt_name == '0089': continue
    # Read niftii image and segmentation
    #print(pt_name)
    img_nib = nib.load(mri_file_paths[eachpatientind])
    seg_nib = nib.load(seg_file_paths[eachpatientind])
    
    #print(pt_name, img_nib.header.get_zooms(), seg_nib.header.get_zooms())
    #print(pt_name, img_nib.shape, seg_nib.shape)

    #if pt_name in ['0140', '0159', '0172']:
        #print(seg_file_paths[eachpatientind].split("\\")[-1])
        #print(pt_name, img_nib.header.get_zooms(), seg_nib.header.get_zooms())
    #else:
    assert img_nib.header.get_zooms() == seg_nib.header.get_zooms()
    assert img_nib.shape == seg_nib.shape

    voxel_sizes = seg_nib.header.get_zooms()
    print(voxel_sizes)

    img = img_nib.get_fdata()
    seg = seg_nib.get_fdata()
    print(np.unique(seg))

    #print('img', img.shape)
    #print('seg', seg.shape)

    cysts = (seg == 5)
    pancreas = (seg == 1)

    labels = sorted(np.unique(seg))
    print("ll",labels)
    if len(labels)==2:
        panc_label = labels[1]
        pancreas = (seg == panc_label)
        cysts = (seg == 9999)



    cysts_b = cysts.astype(int)
    pancreas_b = pancreas.astype(int)
    pancreasandcyst = np.concatenate((cysts_b, pancreas_b))

    # Find Bboxes
    blobs = connected_component_analysis(cysts, thr=0.5)
    num_of_cysts = len(blobs)

    # Calculate the voxel volume (assuming isotropic voxel size)
    voxel_vol_mm3 = voxel_sizes[0] *voxel_sizes[1] * voxel_sizes[2]  # Specify the voxel volume in your desired units

    # Calculate the volume of the segmentation mask
    cysts_volume_ml = get_volume_ml(cysts, voxel_vol_mm3)
    pancreas_volume_ml = get_volume_ml(pancreas, voxel_vol_mm3)

    diagonal_lenght = max(compute_diagonal_length_3D(pancreasandcyst, voxel_sizes[0], voxel_sizes[1], voxel_sizes[2]))
    pancreas_volume_to_diagonal = pancreas_volume_ml / diagonal_lenght

    column_data = ['Allegheny', pt_name, pancreas_volume_ml, cysts_volume_ml, pancreas_volume_ml + cysts_volume_ml, diagonal_lenght, pancreas_volume_to_diagonal, num_of_cysts]

    result = largest3rs(blobs, voxel_sizes)
    # Print the result
    for i, props in enumerate(result, start=1):
        #print(f"Top {i}: Area={props[0]}, Major={props[1]}, Minor={props[2]}")
        area, major, minor = props[0], props[1], props[2]
        column_data.append(area)
        column_data.append(major)
        column_data.append(minor)

    column_data.extend([math.nan] * (17 - len(column_data)))
    #print(column_data)

    df.loc[len(df)] = column_data

df.head()

#plt.show()

21
(1.484375, 1.484375, 6.0)
[0. 1. 5.]
ll [0.0, 1.0, 5.0]
58
(1.125, 1.125, 7.5)
[0. 1. 5.]
ll [0.0, 1.0, 5.0]
41
(1.3671875, 1.3671875, 7.25)
[0. 1. 5.]
ll [0.0, 1.0, 5.0]
80
(0.7813, 0.7813, 6.0)
[0. 1. 5.]
ll [0.0, 1.0, 5.0]
02
(1.40625, 1.40625, 8.400002)
[0. 1. 5.]
ll [0.0, 1.0, 5.0]
11
(1.125, 1.125, 7.5)
[0. 1. 5.]
ll [0.0, 1.0, 5.0]
27
(1.40625, 1.40625, 10.399994)
[0. 1. 5.]
ll [0.0, 1.0, 5.0]
09
(1.5234375, 1.5234375, 6.749999)
[0. 1. 5.]
ll [0.0, 1.0, 5.0]
23
(0.7813, 0.7813, 6.0)
[0. 1. 5.]
ll [0.0, 1.0, 5.0]
61
(1.40625, 1.40625, 8.100002)
[0. 1. 5.]
ll [0.0, 1.0, 5.0]
29
(1.40625, 1.40625, 8.399994)
[0. 1. 5.]
ll [0.0, 1.0, 5.0]
16
(1.125, 1.125, 7.5)
[0. 1. 5.]
ll [0.0, 1.0, 5.0]
51
(0.683594, 0.683594, 6.5)
[0. 1. 5.]
ll [0.0, 1.0, 5.0]
77
(1.125, 1.125, 7.5)
[0. 1. 5.]
ll [0.0, 1.0, 5.0]
12
(1.125, 1.125, 7.7999954)
[0. 1. 5.]
ll [0.0, 1.0, 5.0]
19
(1.171875, 1.171875, 5.200001)
[0. 1. 5.]
ll [0.0, 1.0, 5.0]
48
(0.683594, 0.683594, 6.5)
[0. 1. 5.]
ll [0.0, 1.0, 5.0]
0

Center Patient  Pancreas_volume_ml  Cyst_volume_ml  Panc_Cyst_volume_ml  \
0  Allegheny      21           14.079529        1.864050            15.943579   
1  Allegheny      58           57.086016        0.598008            57.684023   
2  Allegheny      41           32.808695       18.850431            51.659126   
3  Allegheny      80           51.045351        8.215163            59.260514   
4  Allegheny      02           59.485180        7.126261            66.611441   

   Diagonal_mm  Panc_vol_to_Diagonal  Num_of_Cysts  Cyst_1_vol_ml  \
0   103.464935              0.136080            10       0.542029   
1   134.047158              0.425865            22       0.085430   
2   175.794101              0.186631             2      18.782673   
3   160.332947              0.318371            27       4.523284   
4   123.201998              0.482826            19       4.933565   

   Cyst_1_major_mm  Cyst_1_minor_mm  Cyst_2_vol_ml  Cyst_2_major_mm  \
0           41.212         8.236812       1.044397           20.965   
1            7.466         6.714667       0.094922            5.461   
2          141.021        35.281877       0.067759            3.867   
3           32.011        18.867138       0.413871           14.128   
4           41.454        29.950013       0.431895           29.716   

   Cyst_2_minor_mm  Cyst_3_vol_ml  Cyst_3_major_mm  Cyst_3_minor_mm  
0     1.275543e+01       0.185083           18.923              NaN  
1     1.070453e+01       0.037969            4.357     0.000000e+00  
2     0.000000e+00            NaN              NaN              NaN  
3     9.794043e-07       0.307657           13.372     7.996802e-07  
4     1.481029e-06       0.564785           24.484     1.622250e+01

In [27]:
# Save the DataFrame to a CSV file
df.to_csv('server_cyst_segmentation_allegheny.csv', index=False)